// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2RgJ_uIjEufkWbGdvRjBzkXl5NrfcKwk',
    appId: '1:659704987877:web:5ec1f75ab87ee33944940c',
    messagingSenderId: '659704987877',
    projectId: 'persona-srv-301611',
    authDomain: 'persona-srv-301611.firebaseapp.com',
    databaseURL: 'https://persona-srv-301611-default-rtdb.firebaseio.com',
    storageBucket: 'persona-srv-301611.appspot.com',
    measurementId: 'G-6NZYPXPX1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi-Uf13vpp9te4CFdka4s14jkQgdFBsSo',
    appId: '1:659704987877:android:14a1c9118193c1d244940c',
    messagingSenderId: '659704987877',
    projectId: 'persona-srv-301611',
    databaseURL: 'https://persona-srv-301611-default-rtdb.firebaseio.com',
    storageBucket: 'persona-srv-301611.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq0S-tRVqgncxagGf9TTK6o8uZ-GEhdzk',
    appId: '1:659704987877:ios:a6db5edd25cac63844940c',
    messagingSenderId: '659704987877',
    projectId: 'persona-srv-301611',
    databaseURL: 'https://persona-srv-301611-default-rtdb.firebaseio.com',
    storageBucket: 'persona-srv-301611.appspot.com',
    androidClientId: '659704987877-3rgt4munjfcn87pn3bltpdee0pdga1ru.apps.googleusercontent.com',
    iosClientId: '659704987877-sopog619c77lr922bfoaf91llg1tc92e.apps.googleusercontent.com',
    iosBundleId: 'com.persona.flutter-test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq0S-tRVqgncxagGf9TTK6o8uZ-GEhdzk',
    appId: '1:659704987877:ios:29004bb7afa7b66144940c',
    messagingSenderId: '659704987877',
    projectId: 'persona-srv-301611',
    databaseURL: 'https://persona-srv-301611-default-rtdb.firebaseio.com',
    storageBucket: 'persona-srv-301611.appspot.com',
    androidClientId: '659704987877-3rgt4munjfcn87pn3bltpdee0pdga1ru.apps.googleusercontent.com',
    iosClientId: '659704987877-nepofm3r4ovnuklru0i49rqipf7tnn0l.apps.googleusercontent.com',
    iosBundleId: 'io.getstream.streamChatV1',
  );
}
